# Generated by Django 4.2.29 on 2026-03-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluemodel',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cluemodel',
            name='web',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
