# Generated by Django 4.2.29 on 2026-03-30 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_cluemodel_summary_cluemodel_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluemodel',
            name='score',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='cluemodel',
            name='type',
            field=models.CharField(choices=[('scout', 'Scout'), ('entity', 'Entity'), ('unknown', 'Unknown')], default='scout', max_length=16),
        ),
    ]
