# Generated by Django 4.2.29 on 2026-03-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
                ('web', models.CharField(blank=True, max_length=255)),
                ('persona_contacte', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('data_enviat', models.DateField(blank=True, null=True)),
                ('idioma', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('error', 'Error')], default='pending', max_length=16)),
                ('to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachments', models.JSONField(default=list)),
                ('images', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('substitutions', models.JSONField(default=dict)),
                ('attachments', models.JSONField(default=list)),
                ('images', models.JSONField(default=dict)),
            ],
        ),
    ]
