# Generated by Django 4.2.29 on 2026-03-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
