# Generated by Django 4.2.29 on 2026-03-23 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_contactmodel_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailmodel',
            name='to',
        ),
        migrations.AddField(
            model_name='mailmodel',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.contactmodel'),
        ),
    ]
