# Generated by Django 4.2.29 on 2026-03-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_remove_mailmodel_to_mailmodel_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmodel',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='mailing.contactmodel'),
        ),
    ]
