# Generated by Django 4.2.29 on 2026-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailmodel_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='relevant',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mailmodel',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='mailmodel',
            name='images',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='images',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='templatemodel',
            name='substitutions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
